cluster:
  clusterSpec:
    replicas: 3
    additionalStartArgs:
      - '--ignore=thp'
    image:
      repository: "voltdb/voltdb-enterprise"
      tag: "10.2.5"
      pullPolicy: "Always"
    persistentVolume:
      size: "4Gi"
    deletePVC: 'true'
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    nodeSelector:
      env: "db"
  config:
    deployment:
      cluster:
        kfactor: 1
        sitesperhost: 4
      commandlog:
        enabled: 'false'
        synchronous: 'false'
        logsize: 3072
        frequency:
           time: 5000
      snapshot:
        enabled: 'false'
        frequency: '24h'
        prefix: 'SNAP'
        retain: '2'
      dr:
        id: 1
        role: 'xdcr'
        connection:
          enabled: true
  serviceSpec:
    dr:
    # prevent the dr discovery service from being created, it's not needed
      enabled: false
      annotations:
        cluster2-key1: "an annotation for cluster2 dr services"
    perpod:
      type: NodePort
      dr:
        enabled: true
        externalTrafficPolicy: Local
        startReplicationNodePort: 31310
